[package]
name = "merak-core"
version = "0.1.0-alpha.0"
edition = "2024"

[dependencies]
surrealdb = "2.5.0"
merak-macros = { version = "0.1.0-alpha.0", path = "../macros" }
serde = { version = "1.0.228", features = ["derive"] }
